module-05/time_to_answer/config/routes.rb
Rails.application.routes.draw do
  namespace :users_backoffice do
    get 'welcome/index'
  end
  
  namespace :site do
    get 'welcome/index'
  end

  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    resources :admins # Administradores
    resources :subjects # Assuntos/Áreas
    resources :questions # Perguntas
  end

  devise_for :admins
  devise_for :users
  
  get 'inicio', to: 'site/welcome#index'
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

module-05/time_to_answer/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Kaminari
  paginates_per 5
end

module-05/time_to_answer/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

module-05/time_to_answer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

module-05/time_to_answer/app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

module-05/time_to_answer/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  # Kaminari
  paginates_per 5
end

module-05/time_to_answer/app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
end

module-05/time_to_answer/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

module-05/time_to_answer/app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

module-05/time_to_answer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource

    protected
    
      def layout_by_resource
        devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
      end
end

module-05/time_to_answer/app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.includes(:answers).page(params[:page])
  end
end

module-05/time_to_answer/app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

module-05/time_to_answer/app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

module-05/time_to_answer/app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

module-05/time_to_answer/app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

module-05/time_to_answer/app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        (object && method) ? object.model.human_attribute_name(method) : "Informe os parâmetros corretamente!"
    end
end

module-05/time_to_answer/app/helpers/application_helper.rb
module ApplicationHelper
end

module-05/time_to_answer/app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

module-05/time_to_answer/app/helpers/site_helper.rb
module SiteHelper
end

module-05/time_to_answer/app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

module-05/time_to_answer/app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

module-05/time_to_answer/app/views/admins_backoffice/admins/shared/_form.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= action_message %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">

    <% if @admin.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            
            <ul>
              <% @admin.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
        </div>
    <% end %>

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= @admin.model_name.human %>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                       <%= form_with(model: [ :admins_backoffice, @admin ], local: true) do |form| %>
                        
                            <div class="form-group">
                                <%= form.label :email %>
                                <%= form.text_field :email, 
                                         class:"form-control", 
                                        placeholder: t('placeholder.admin_email')  %>
                            </div>
                            
                            <div class="form-group">
                                <%= form.label :password %>
                                <%= form.password_field :password, 
                                         class:"form-control", 
                                         placeholder: t('placeholder.admin_password')  %>
                            </div>

                            <div class="form-group">
                                <%= form.label :password_confirmation %>
                                <%= form.password_field :password_confirmation, 
                                         class:"form-control", 
                                         placeholder: t('placeholder.admin_password_confirmation')  %>
                            </div>

                            <button type="submit" class="btn btn-default">
                              <%= t('button.save') %>
                            </button>
                        <% end %>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

module-05/time_to_answer/app/views/layouts/admin_devise.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'admin_devise' %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admin_devise' %>
    <% if flash %>
        <% flash.each do |key, value| %>
          <%= javascript_tag do %>
              $.bootstrapGrowl('<%= value %>', {
              type: 'danger', // (null, 'info', 'danger', 'success')
              align: 'right', // ('left', 'right', or 'center')
              allow_dismiss: true, // If true then will display a cross to close the popup.
              stackup_spacing: 10 // spacing between consecutively stacked growls.
              });
          <% end %>
        <% end %>
    <% end %>
</body>

</html>

module-05/time_to_answer/app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'admins_backoffice' %>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Backoffice Administrativo</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">                               
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <%= link_to destroy_admin_session_path, method: :delete do %>
                                <i class="fa fa-sign-out fa-fw"></i> Sair
                            <% end %>
                        </li>   
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <%= link_to admins_backoffice_welcome_index_path do %>
                                <i class="fa fa-dashboard fa-fw"></i> Dashboard
                            <% end %>
                        </li>
	
                        <li>
                            <%= link_to admins_backoffice_admins_path do %>
                                <i class="fa fa-users fa-fw"></i> Administradores
                            <% end %>
                        </li>
                        
                        <li>
                            <%= link_to admins_backoffice_subjects_path do %>
                                <i class="fa fa-file-text-o fa-fw"></i> Assuntos/Áreas
                            <% end %>
                        </li> 
                        
                        <li>
                            <%= link_to admins_backoffice_questions_path do %>
                                <i class="fa fa-th-list fa-fw"></i> Perguntas
                            <% end %>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admins_backoffice' %>

    <% if notice %>
        <%= javascript_tag do %>
            $.bootstrapGrowl('<%= notice %>', {
            type: 'success', // (null, 'info', 'danger', 'success')
            align: 'right', // ('left', 'right', or 'center')
            allow_dismiss: true, // If true then will display a cross to close the popup.
            stackup_spacing: 10 // spacing between consecutively stacked growls.
            });
        <% end %>
    <% end %>

</body>

</html>

module-05/time_to_answer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>LAYOUT APPLICATION</h1>
    <%= yield %>
  </body>
</html>

module-05/time_to_answer/app/views/layouts/profiles_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>LAYOUT PROFILES BACKOFFICE</h1>
    <%= yield %>
  </body>
</html>

module-05/time_to_answer/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'site' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Time to Answer</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav"></ul>
            <ul class="nav navbar-nav navbar-right">
              <% unless user_signed_in? %>
                <li><%= link_to 'Entrar', new_user_session_path %></li>
                <li><%= link_to 'Cadastrar-se', new_user_registration_path %></li>
              <% else%>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to users_backoffice_welcome_index_path do %>
                          <i class="fa fa-user fa-fw"></i> Perfil
                      <% end %>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                          <i class="fa fa-sign-out fa-fw"></i> Sair
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Site::Welcome#index</h1>
        <p>Find me in app/views/site/welcome/index.html.erb</p>

        <% if user_signed_in? %>
          <p>Usuário ESTÁ logado / <%= current_user.email %> </p>
        <% else %>
          <p>Usuário NÃO está logado</p>
        <% end %>
        <% if admin_signed_in? %>
          <p>Administrador ESTÁ logado / <%= current_admin.email %> </p>
        <% else %>
          <p>Administrador NÃO está logado</p>
        <% end %>
      </div>

      <%= yield %>
    </div> <!-- /container -->


    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>
    <% if notice %>
        <%= javascript_tag do %>
            $.bootstrapGrowl('<%= notice %>', {
            type: 'success', // (null, 'info', 'danger', 'success')
            align: 'right', // ('left', 'right', or 'center')
            allow_dismiss: true, // If true then will display a cross to close the popup.
            stackup_spacing: 10 // spacing between consecutively stacked growls.
            });
        <% end %>
    <% end %>
  </body>
</html>

module-05/time_to_answer/app/views/layouts/user_devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'user_devise' %>
  </head>

  <body class="login">
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'user_devise' %>
    <% if flash %>
        <% flash.each do |key, value| %>
          <%= javascript_tag do %>
              $.bootstrapGrowl('<%= value %>', {
              type: 'danger', // (null, 'info', 'danger', 'success')
              align: 'right', // ('left', 'right', or 'center')
              allow_dismiss: true, // If true then will display a cross to close the popup.
              stackup_spacing: 10 // spacing between consecutively stacked growls.
              });
          <% end %>
        <% end %>
    <% end %>
  </body>
</html>